const ServiceController = require('../controllers/ServiceController')
const isAuthenticated = require('../policies/isAuthenticated')

module.exports = (app) => {
  app.post('/addservice', isAuthenticated, ServiceController.addService)
  app.post('/getservices', isAuthenticated, ServiceController.getServices)
  app.post('/getservice', isAuthenticated, ServiceController.getService)
  app.post('/editservice', isAuthenticated, ServiceController.editService)
  app.post('/archiveservice', isAuthenticated, ServiceController.archiveService)
  app.post('/getservsforcoupons', isAuthenticated, ServiceController.getServsForCoupons)
  app.post('/getservsusinghistory', isAuthenticated, ServiceController.getServsUsingHistory)
  app.post('/getnotifications', isAuthenticated, ServiceController.getNotifications)
  app.post('/getreleased', isAuthenticated, ServiceController.getReleased)
  app.post('/getnotification', isAuthenticated, ServiceController.getNotification)
  app.post('/approvenotification', isAuthenticated, ServiceController.approveNotification)
  app.post('/cancelnotification', isAuthenticated, ServiceController.cancelNotification)
  app.post('/getapproved', isAuthenticated, ServiceController.getApproved)
  app.post('/donutservice', isAuthenticated, ServiceController.donutService)
  app.post('/gettakons', isAuthenticated, ServiceController.getTakons)
  app.post('/getadminservices', isAuthenticated, ServiceController.getAdminServices)
  app.post('/aprovecreation', isAuthenticated, ServiceController.aproveCreation)
  app.post('/canselcreation', isAuthenticated, ServiceController.canselCreation)
  app.post('/getownreleased', isAuthenticated, ServiceController.getOwnReleased)
  app.post('/minustakons', isAuthenticated, ServiceController.minusTakons)
  app.post('/transfertakonstomany', isAuthenticated, ServiceController.transferTakons)
}
